### ISSUE TITLE
Support for non-Android Gradle builds

### ISSUE THREAD

**Issue by HoldYourWaffle** [mhashim6/intellij-drumroll#8]
The title pretty much says it all, unfortunately all my projects use Gradle nowadays :(

![My disappointment is immeasurable, and my day is ruined](https://i.kym-cdn.com/entries/icons/mobile/000/025/543/eca.jpg)

Similar to #3. https://github.com/mhashim6/intellij-drumroll/commit/e596e1aea608683af53b43cea0ab84f85e731d54 added support for Android builds, but (un)fortunately I'm not an Android developer...

**Comment by mhashim6** [comment]
@HoldYourWaffle Your comment brought me joy!
I created a [PR](https://github.com/mhashim6/intellij-drumroll/pull/9) here to tackle this issue, I will appreciate your testing.

**Comment by HoldYourWaffle** [comment]
Great to hear my comment had an impact :)

Unfortuantely, when I try to build my project I get this notification:
![afbeelding](https://user-images.githubusercontent.com/11472320/190917543-e38ee137-a9a3-485e-8337-28f2e64cfeb9.png)

In the logs I found the following exception(s):
```
2022-09-18 18:22:14,024 [  25629]   INFO - #c.i.e.r.ExecutionUtil - Error running 'Build ...':<br>jaco/mp3/player/MP3Player
java.lang.NoClassDefFoundError: jaco/mp3/player/MP3Player
	at PlayerKt.<clinit>(Player.kt:7)
	at Drumroll$Companion$Listener.processStarted(Drumroll.kt:60)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:625)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:399)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:378)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:437)
	at jdk.proxy1/jdk.proxy1.$Proxy209.processStarted(Unknown Source)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1$2$1.run(ExecutionManagerImpl.kt:258)
	at com.intellij.ui.AppUIUtil.invokeLaterIfProjectAlive(AppUIUtil.java:196)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1$2.accept(ExecutionManagerImpl.kt:236)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1$2.accept(ExecutionManagerImpl.kt:72)
	at org.jetbrains.concurrency.DonePromise.onSuccess(promise.kt:348)
	at org.jetbrains.concurrency.DonePromise.onSuccess(promise.kt:317)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:235)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: jaco.mp3.player.MP3Player PluginClassLoader(plugin=PluginDescriptor(name=Drum-Roll, id=mhashim6.idea.plugin.drumroll, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4167.29.plugins\Drum-Roll-1.0.jar, version=1.0, package=null, isBundled=false), packagePrefix=null, instanceId=70, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:214)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 47 more
2022-09-18 18:22:14,251 [  25856]   INFO - #o.j.p.g.GradleManager - Instructing gradle to use java from C:\Program Files\Java\jdk-17.0.2
2022-09-18 18:22:14,274 [  25879]   INFO - #o.j.p.g.GradleManager - Instructing gradle to use java from C:\Program Files\Java\jdk-17.0.2
2022-09-18 18:22:14,322 [  25927]   INFO - #o.j.p.g.s.e.GradleExecutionHelper - Gradle system adjuster service: org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper$SystemPropertiesAdjuster
2022-09-18 18:22:15,746 [  27351]   INFO - #o.j.p.g.s.e.GradleExecutionHelper - Passing command-line args to Gradle Tooling API: --init-script C:\Users\Ravi\AppData\Local\Temp\ijmapper.gradle --init-script C:\Users\Ravi\AppData\Local\Temp\ijresolvers.gradle
2022-09-18 18:22:26,444 [  38049]   INFO - STDERR - Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.nio.channels.AsynchronousCloseException
2022-09-18 18:22:26,445 [  38050]   INFO - STDERR - 	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:62)
2022-09-18 18:22:26,445 [  38050]   INFO - STDERR - 	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
2022-09-18 18:22:26,445 [  38050]   INFO - STDERR - 	at org.gradle.util.internal.DisconnectableInputStream$1.run(DisconnectableInputStream.java:127)
2022-09-18 18:22:26,446 [  38051]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-09-18 18:22:26,446 [  38051]   INFO - STDERR - Caused by: java.nio.channels.AsynchronousCloseException
2022-09-18 18:22:26,446 [  38051]   INFO - STDERR - 	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
2022-09-18 18:22:26,446 [  38051]   INFO - STDERR - 	at java.base/sun.nio.ch.SocketChannelImpl.endRead(SocketChannelImpl.java:389)
2022-09-18 18:22:26,446 [  38051]   INFO - STDERR - 	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:428)
2022-09-18 18:22:26,446 [  38051]   INFO - STDERR - 	at java.base/sun.nio.ch.SourceChannelImpl.read(SourceChannelImpl.java:113)
2022-09-18 18:22:26,447 [  38052]   INFO - STDERR - 	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:59)
2022-09-18 18:22:26,447 [  38052]   INFO - STDERR - 	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)
2022-09-18 18:22:26,447 [  38052]   INFO - STDERR - 	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)
2022-09-18 18:22:26,447 [  38052]   INFO - STDERR - 	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
2022-09-18 18:22:26,447 [  38052]   INFO - STDERR - 	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
2022-09-18 18:22:26,448 [  38053]   INFO - STDERR - 	at org.gradle.util.internal.DisconnectableInputStream$1.run(DisconnectableInputStream.java:98)
2022-09-18 18:22:26,448 [  38053]   INFO - STDERR - 	... 1 more
2022-09-18 18:22:47,706 [  59311]   INFO - #c.i.c.ComponentStoreImpl - Saving appFileTypeManager took 14 ms
2022-09-18 18:22:48,118 [  59723]   INFO - #c.i.c.ComponentStoreImpl - Saving Project(name=..., containerState=COMPONENT_CREATED, componentStore=...)RunManager took 22 ms
```

When building the plugin I also got some strange errors, but the build seems to succeed anyway:
```
> Configure project :
[gradle-intellij-plugin :Drum-Roll] Gradle IntelliJ Plugin is outdated: 1.7.0. Update `org.jetbrains.intellij` to: 1.9.0

> Task :clean
> Task :setupDependencies
> Task :setupInstrumentCode

> Task :patchPluginXml
[gradle-intellij-plugin :Drum-Roll:patchPluginXml] Patching plugin.xml: attribute 'since-build=[201.6668.113]' of 'idea-version' tag will be set to '213'
[gradle-intellij-plugin :Drum-Roll:patchPluginXml] Patching plugin.xml: value of 'version[1.1]' tag will be set to '1.0'

> Task :processResources
> Task :processTestResources NO-SOURCE
> Task :compileKotlin
> Task :compileJava NO-SOURCE
> Task :classes
> Task :instrumentCode
> Task :postInstrumentCode
> Task :inspectClassesForKotlinIC
> Task :jar
> Task :prepareSandbox

> Task :buildSearchableOptions
WARNING: package com.apple.laf not in java.desktop
WARNING: package com.apple.eawt.event not in java.desktop
WARNING: package com.apple.eawt not in java.desktop
WARNING: package sun.lwawt.macosx not in java.desktop
WARNING: package sun.lwawt not in java.desktop
Starting searchable options index builder
2022-09-18 17:42:16,532 [   3865]   WARN - l.NotificationGroupManagerImpl - Notification group CodeWithMe is already registered (group=com.intellij.notification.NotificationGroup@248c0349). Plugin descriptor: PluginDescriptor(name=Code With Me, id=com.jetbrains.codeWithMe, descriptorPath=plugin.xml, path=~\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2021.3\75777e10a0e2880bc02945066dda2480a696c3d9\ideaIC-2021.3\plugins\cwm-plugin, version=213.5744.223, package=null, isBundled=true) 
2022-09-18 17:42:36,211 [  23544]   WARN - #com.intellij.ui.jcef.JBCefApp - JCEF is manually disabled in headless env via 'ide.browser.jcef.headless.enabled=false' 
Found 213 configurables
Searchable options index builder completed
2022-09-18 17:42:39,500 [  26833]  ERROR - tellij.openapi.util.ObjectTree - fleet/rpc/client/FleetWebSocketTransportKt 
java.lang.NoClassDefFoundError: fleet/rpc/client/FleetWebSocketTransportKt
	at com.intellij.wsl.fs.WslFsdServerHub.shutdown(WslFsdServerHub.kt:22)
	at com.intellij.wsl.fs.WslContentLoader$dispose$1$1.invokeSuspend(WslContentLoader.kt:109)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.wsl.fs.WslContentLoader.dispose(WslContentLoader.kt:108)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:136)
	at com.intellij.openapi.util.ObjectTree.executeAllChildren(ObjectTree.java:153)
	at com.intellij.openapi.util.Disposer.disposeChildren(Disposer.java:165)
	at com.intellij.serviceContainer.ComponentManagerImpl.startDispose(ComponentManagerImpl.kt:1077)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$disposeContainer$3(ApplicationImpl.java:193)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:947)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeContainer(ApplicationImpl.java:192)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:213)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:601)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$exit$8(ApplicationImpl.java:557)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: fleet.rpc.client.FleetWebSocketTransportKt PluginClassLoader(plugin=PluginDescriptor(name=WSL File System Support, id=org.jetbrains.plugins.wsl.fs, descriptorPath=plugin.xml, path=~\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2021.3\75777e10a0e2880bc02945066dda2480a696c3d9\ideaIC-2021.3\plugins\wsl-fs-helper, version=213.5744.223, package=com.intellij.wsl.fs, isBundled=true), packagePrefix=com.intellij.wsl.fs., instanceId=8, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 50 more
2022-09-18 17:42:39,501 [  26834]  ERROR - tellij.openapi.util.ObjectTree - IntelliJ IDEA 2021.3  Build #IC-213.5744.223 
2022-09-18 17:42:39,502 [  26835]  ERROR - tellij.openapi.util.ObjectTree - JDK: 11.0.13; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2022-09-18 17:42:39,502 [  26835]  ERROR - tellij.openapi.util.ObjectTree - OS: Windows 10 
2022-09-18 17:42:39,503 [  26836]  ERROR - tellij.openapi.util.ObjectTree - Last Action:  

> Task :jarSearchableOptions
[gradle-intellij-plugin :Drum-Roll:jarSearchableOptions] No searchable options found. If plugin is not supposed to provide custom settings exposed in UI, disable building searchable options to decrease the build time. See: https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin-faq.html#how-to-disable-building-searchable-options

> Task :buildPlugin
> Task :assemble
> Task :compileTestKotlin NO-SOURCE
> Task :compileTestJava NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :instrumentTestCode
> Task :postInstrumentTestCode
> Task :prepareTestingSandbox
> Task :test NO-SOURCE
> Task :classpathIndexCleanup SKIPPED
> Task :check UP-TO-DATE
> Task :build

BUILD SUCCESSFUL in 34s
17 actionable tasks: 17 executed
```

**Comment by mhashim6** [comment]
@HoldYourWaffle Thank you for the logs! How did you install the plugin? Did you build a jar and load it into your idea instance?

If that's the case, then build the jar using
``` shell
./gradlew buildPlugin
```

and locate the jar in `build/distributions/`
